export type Category =
  | "All"
  | "AI x Crypto"
  | "TradFi"
  | "DeFi"
  | "Memecoins"
  | "Infrastructure"
  | "L1"
  | "L2"
  | "DePIN"
  | "RWA"
  | "Prediction Markets"
  | "Wallets"
  | "Trading"
  | "DEX"
  | "NFT"
  | "Gaming"
  | "SocialFi"
  | "Other";

export interface LeaderboardProject {
  id: string;
  slug: string;
  name: string;
  domain: string;
  url: string;
  description: string;
  category: Exclude<Category, "All">;
  totalBidUsdt: number;
  rankingTimestamp: string;
  clickCount: number;
  logoText: string;
  previousRank?: number;
}

export const categories: Category[] = [
  "All",
  "AI x Crypto",
  "TradFi",
  "DeFi",
  "Memecoins",
  "Infrastructure",
  "L1",
  "L2",
  "DePIN",
  "RWA",
  "Prediction Markets",
  "Wallets",
  "Trading",
  "DEX",
  "NFT",
  "Gaming",
  "SocialFi",
  "Other",
];

export const developmentProjects: LeaderboardProject[] = [
  {
    id: "uniswap",
    slug: "uniswap",
    name: "Uniswap",
    domain: "uniswap.org",
    url: "https://uniswap.org",
    description: "Decentralized exchange protocol for token swaps and liquidity markets.",
    category: "DeFi",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-08-22T12:05:00.000Z",
    clickCount: 48210,
    logoText: "UN",
    previousRank: 2,
  },
  {
    id: "hyperliquid",
    slug: "hyperliquid",
    name: "Hyperliquid",
    domain: "hyperliquid.xyz",
    url: "https://hyperliquid.xyz",
    description: "On-chain perpetual exchange and liquidity network for advanced crypto trading.",
    category: "DEX",
    totalBidUsdt: 34,
    rankingTimestamp: "2026-09-04T08:00:00.000Z",
    clickCount: 0,
    logoText: "HL",
  },
  {
    id: "eigenlayer",
    slug: "eigenlayer",
    name: "EigenLayer",
    domain: "eigenlayer.xyz",
    url: "https://www.eigenlayer.xyz",
    description: "Ethereum restaking infrastructure for shared security and actively validated services.",
    category: "Infrastructure",
    totalBidUsdt: 29,
    rankingTimestamp: "2026-09-04T08:01:00.000Z",
    clickCount: 0,
    logoText: "EIG",
  },
  {
    id: "pendle",
    slug: "pendle",
    name: "Pendle",
    domain: "pendle.finance",
    url: "https://www.pendle.finance",
    description: "DeFi protocol for tokenizing and trading future yield across crypto assets.",
    category: "DeFi",
    totalBidUsdt: 24,
    rankingTimestamp: "2026-09-04T08:02:00.000Z",
    clickCount: 0,
    logoText: "PEND",
  },
  {
    id: "mantle",
    slug: "mantle",
    name: "Mantle",
    domain: "mantle.xyz",
    url: "https://www.mantle.xyz",
    description: "Ethereum layer two ecosystem for low-cost applications, liquidity, and on-chain products.",
    category: "L2",
    totalBidUsdt: 21,
    rankingTimestamp: "2026-09-04T08:03:00.000Z",
    clickCount: 0,
    logoText: "MNT",
  },
  {
    id: "ethena",
    slug: "ethena",
    name: "Ethena",
    domain: "ethena.fi",
    url: "https://ethena.fi",
    description: "Synthetic dollar protocol and internet bond products built for crypto-native finance.",
    category: "DeFi",
    totalBidUsdt: 18,
    rankingTimestamp: "2026-09-04T08:04:00.000Z",
    clickCount: 0,
    logoText: "ENA",
  },
  {
    id: "okx",
    slug: "okx",
    name: "OKX",
    domain: "okx.com",
    url: "https://www.okx.com",
    description: "Crypto exchange and Web3 platform for spot, derivatives, wallet, and DeFi access.",
    category: "Trading",
    totalBidUsdt: 30,
    rankingTimestamp: "2026-09-04T00:00:00.000Z",
    clickCount: 0,
    logoText: "OKX",
  },
  {
    id: "robinhood",
    slug: "robinhood",
    name: "Robinhood",
    domain: "robinhood.com",
    url: "https://robinhood.com",
    description: "Trading platform for stocks, crypto, options, and financial accounts.",
    category: "TradFi",
    totalBidUsdt: 25,
    rankingTimestamp: "2026-09-04T00:01:00.000Z",
    clickCount: 0,
    logoText: "R",
  },
  {
    id: "kraken",
    slug: "kraken",
    name: "Kraken",
    domain: "kraken.com",
    url: "https://www.kraken.com",
    description: "Crypto exchange for spot trading, staking, futures, and institutional services.",
    category: "Trading",
    totalBidUsdt: 22,
    rankingTimestamp: "2026-09-04T00:02:00.000Z",
    clickCount: 0,
    logoText: "KR",
  },
  {
    id: "avalanche",
    slug: "avalanche",
    name: "Avalanche",
    domain: "avax.network",
    url: "https://www.avax.network",
    description: "Layer one blockchain platform for custom networks and high-throughput applications.",
    category: "L1",
    totalBidUsdt: 20,
    rankingTimestamp: "2026-09-04T00:03:00.000Z",
    clickCount: 0,
    logoText: "AVAX",
  },
  {
    id: "sui",
    slug: "sui",
    name: "Sui",
    domain: "sui.io",
    url: "https://sui.io",
    description: "Layer one blockchain designed for fast object-based smart contract applications.",
    category: "L1",
    totalBidUsdt: 19,
    rankingTimestamp: "2026-09-04T00:04:00.000Z",
    clickCount: 0,
    logoText: "SUI",
  },
  {
    id: "polygon",
    slug: "polygon",
    name: "Polygon",
    domain: "polygon.technology",
    url: "https://polygon.technology",
    description: "Ethereum scaling ecosystem for proof-of-stake, zk, and app-chain infrastructure.",
    category: "L2",
    totalBidUsdt: 18,
    rankingTimestamp: "2026-09-04T00:05:00.000Z",
    clickCount: 0,
    logoText: "POL",
  },
  {
    id: "starknet",
    slug: "starknet",
    name: "Starknet",
    domain: "starknet.io",
    url: "https://www.starknet.io",
    description: "Ethereum layer two network using validity proofs for scalable smart contracts.",
    category: "L2",
    totalBidUsdt: 17,
    rankingTimestamp: "2026-09-04T00:06:00.000Z",
    clickCount: 0,
    logoText: "STRK",
  },
  {
    id: "the-graph",
    slug: "the-graph",
    name: "The Graph",
    domain: "thegraph.com",
    url: "https://thegraph.com",
    description: "Decentralized indexing protocol for querying blockchain data across networks.",
    category: "Infrastructure",
    totalBidUsdt: 16,
    rankingTimestamp: "2026-09-04T00:07:00.000Z",
    clickCount: 0,
    logoText: "GRT",
  },
  {
    id: "filecoin",
    slug: "filecoin",
    name: "Filecoin",
    domain: "filecoin.io",
    url: "https://filecoin.io",
    description: "Decentralized storage network for open data, applications, and verifiable storage.",
    category: "DePIN",
    totalBidUsdt: 15,
    rankingTimestamp: "2026-09-04T00:08:00.000Z",
    clickCount: 0,
    logoText: "FIL",
  },
  {
    id: "akash-network",
    slug: "akash-network",
    name: "Akash Network",
    domain: "akash.network",
    url: "https://akash.network",
    description: "Decentralized cloud compute marketplace for deploying applications and AI workloads.",
    category: "DePIN",
    totalBidUsdt: 14,
    rankingTimestamp: "2026-09-04T00:09:00.000Z",
    clickCount: 0,
    logoText: "AKT",
  },
  {
    id: "lido",
    slug: "lido",
    name: "Lido",
    domain: "lido.fi",
    url: "https://lido.fi",
    description: "Liquid staking protocol for Ethereum and other proof-of-stake networks.",
    category: "DeFi",
    totalBidUsdt: 13,
    rankingTimestamp: "2026-09-04T00:10:00.000Z",
    clickCount: 0,
    logoText: "LDO",
  },
  {
    id: "makerdao",
    slug: "makerdao",
    name: "MakerDAO",
    domain: "makerdao.com",
    url: "https://makerdao.com",
    description: "Decentralized credit protocol and stablecoin system for on-chain finance.",
    category: "DeFi",
    totalBidUsdt: 12,
    rankingTimestamp: "2026-09-04T00:11:00.000Z",
    clickCount: 0,
    logoText: "MKR",
  },
  {
    id: "curve",
    slug: "curve",
    name: "Curve Finance",
    domain: "curve.fi",
    url: "https://curve.fi",
    description: "Decentralized exchange focused on stablecoin swaps and deep liquidity markets.",
    category: "DEX",
    totalBidUsdt: 11,
    rankingTimestamp: "2026-09-04T00:12:00.000Z",
    clickCount: 0,
    logoText: "CRV",
  },
  {
    id: "dydx",
    slug: "dydx",
    name: "dYdX",
    domain: "dydx.exchange",
    url: "https://dydx.exchange",
    description: "Decentralized exchange for perpetual futures and advanced crypto trading.",
    category: "DEX",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-04T00:13:00.000Z",
    clickCount: 0,
    logoText: "DYDX",
  },
  {
    id: "magic-eden",
    slug: "magic-eden",
    name: "Magic Eden",
    domain: "magiceden.io",
    url: "https://magiceden.io",
    description: "NFT marketplace for collecting, minting, and trading digital assets across chains.",
    category: "NFT",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-04T00:14:00.000Z",
    clickCount: 0,
    logoText: "ME",
  },
  {
    id: "axie-infinity",
    slug: "axie-infinity",
    name: "Axie Infinity",
    domain: "axieinfinity.com",
    url: "https://axieinfinity.com",
    description: "Blockchain game ecosystem centered on collectible creatures, battles, and digital ownership.",
    category: "Gaming",
    totalBidUsdt: 9,
    rankingTimestamp: "2026-09-04T00:15:00.000Z",
    clickCount: 0,
    logoText: "AXS",
  },
  {
    id: "farcaster",
    slug: "farcaster",
    name: "Farcaster",
    domain: "farcaster.xyz",
    url: "https://www.farcaster.xyz",
    description: "Decentralized social protocol for user-owned identity and social applications.",
    category: "SocialFi",
    totalBidUsdt: 8,
    rankingTimestamp: "2026-09-04T00:16:00.000Z",
    clickCount: 0,
    logoText: "FC",
  },
  {
    id: "shiba-inu",
    slug: "shiba-inu",
    name: "Shiba Inu",
    domain: "shibatoken.com",
    url: "https://shibatoken.com",
    description: "Community-driven memecoin ecosystem with tokens, DeFi, and NFT products.",
    category: "Memecoins",
    totalBidUsdt: 7,
    rankingTimestamp: "2026-09-04T00:17:00.000Z",
    clickCount: 0,
    logoText: "SHIB",
  },
  {
    id: "uma",
    slug: "uma",
    name: "UMA",
    domain: "uma.xyz",
    url: "https://uma.xyz",
    description: "Optimistic oracle infrastructure used by prediction markets and on-chain applications.",
    category: "Prediction Markets",
    totalBidUsdt: 6,
    rankingTimestamp: "2026-09-04T00:18:00.000Z",
    clickCount: 0,
    logoText: "UMA",
  },
  {
    id: "centrifuge",
    slug: "centrifuge",
    name: "Centrifuge",
    domain: "centrifuge.io",
    url: "https://centrifuge.io",
    description: "Real-world asset protocol connecting credit markets with on-chain liquidity.",
    category: "RWA",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-09-04T00:19:00.000Z",
    clickCount: 0,
    logoText: "CFG",
  },
  {
    id: "bittensor",
    slug: "bittensor",
    name: "Bittensor",
    domain: "bittensor.com",
    url: "https://bittensor.com",
    description: "Open network for decentralized machine intelligence and tokenized AI markets.",
    category: "AI x Crypto",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:00:00.000Z",
    clickCount: 0,
    logoText: "TA",
    previousRank: 1,
  },
  {
    id: "ethereum",
    slug: "ethereum",
    name: "Ethereum",
    domain: "ethereum.org",
    url: "https://ethereum.org",
    description: "Layer one blockchain and smart contract platform for decentralized applications.",
    category: "L1",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:02:00.000Z",
    clickCount: 0,
    logoText: "ETH",
  },
  {
    id: "optimism",
    slug: "optimism",
    name: "Optimism",
    domain: "optimism.io",
    url: "https://optimism.io",
    description: "Ethereum layer two network and ecosystem built around the OP Stack.",
    category: "L2",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:03:00.000Z",
    clickCount: 0,
    logoText: "OP",
  },
  {
    id: "chainlink",
    slug: "chainlink",
    name: "Chainlink",
    domain: "chain.link",
    url: "https://chain.link",
    description: "Oracle infrastructure connecting smart contracts with off-chain data.",
    category: "Infrastructure",
    totalBidUsdt: 20,
    rankingTimestamp: "2026-08-21T23:41:00.000Z",
    clickCount: 21109,
    logoText: "CL",
    previousRank: 4,
  },
  {
    id: "solana",
    slug: "solana",
    name: "Solana",
    domain: "solana.com",
    url: "https://solana.com",
    description: "High-throughput layer one blockchain for consumer and financial applications.",
    category: "L1",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-20T17:18:00.000Z",
    clickCount: 17640,
    logoText: "SOL",
  },
  {
    id: "arbitrum",
    slug: "arbitrum",
    name: "Arbitrum",
    domain: "arbitrum.io",
    url: "https://arbitrum.io",
    description: "Ethereum layer two ecosystem for scalable smart contract applications.",
    category: "L2",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-20T10:30:00.000Z",
    clickCount: 15502,
    logoText: "ARB",
  },
  {
    id: "dogecoin",
    slug: "dogecoin",
    name: "Dogecoin",
    domain: "dogecoin.com",
    url: "https://dogecoin.com",
    description: "Open-source peer-to-peer digital currency with a large community.",
    category: "Memecoins",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-08-19T15:46:00.000Z",
    clickCount: 10118,
    logoText: "DOGE",
  },
  {
    id: "render",
    slug: "render-network",
    name: "Render Network",
    domain: "rendernetwork.com",
    url: "https://rendernetwork.com",
    description: "Decentralized GPU rendering and compute network for creators.",
    category: "DePIN",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-19T09:00:00.000Z",
    clickCount: 8920,
    logoText: "RN",
  },
  {
    id: "ondo",
    slug: "ondo-finance",
    name: "Ondo Finance",
    domain: "ondo.finance",
    url: "https://ondo.finance",
    description: "Tokenized real-world asset products and institutional on-chain finance.",
    category: "RWA",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-09-03T00:05:00.000Z",
    clickCount: 0,
    logoText: "ONDO",
  },
  {
    id: "helium",
    slug: "helium",
    name: "Helium",
    domain: "helium.com",
    url: "https://www.helium.com",
    description: "Decentralized wireless network for IoT and mobile connectivity.",
    category: "DePIN",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-09-03T00:04:00.000Z",
    clickCount: 0,
    logoText: "HNT",
  },
  {
    id: "polymarket",
    slug: "polymarket",
    name: "Polymarket",
    domain: "polymarket.com",
    url: "https://polymarket.com",
    description: "Prediction market platform for trading event outcome probabilities.",
    category: "Prediction Markets",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-18T13:35:00.000Z",
    clickCount: 6980,
    logoText: "PM",
  },
  {
    id: "azuro",
    slug: "azuro",
    name: "Azuro",
    domain: "azuro.org",
    url: "https://azuro.org",
    description: "On-chain prediction market liquidity and tooling protocol.",
    category: "Prediction Markets",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:06:00.000Z",
    clickCount: 0,
    logoText: "AZ",
  },
  {
    id: "phantom",
    slug: "phantom",
    name: "Phantom",
    domain: "phantom.com",
    url: "https://phantom.com",
    description: "Crypto wallet for managing tokens, NFTs, and multi-chain apps.",
    category: "Wallets",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-18T08:12:00.000Z",
    clickCount: 6592,
    logoText: "PH",
  },
  {
    id: "binance",
    slug: "binance",
    name: "Binance",
    domain: "binance.com",
    url: "https://www.binance.com",
    description: "Global crypto trading venue for spot, derivatives, and Web3 products.",
    category: "Trading",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-08-17T21:30:00.000Z",
    clickCount: 6120,
    logoText: "BN",
  },
  {
    id: "jupiter",
    slug: "jupiter",
    name: "Jupiter",
    domain: "jup.ag",
    url: "https://jup.ag",
    description: "Solana liquidity aggregator for swaps, limit orders, and trading tools.",
    category: "DEX",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-17T16:24:00.000Z",
    clickCount: 5774,
    logoText: "JUP",
  },
  {
    id: "pancakeswap",
    slug: "pancakeswap",
    name: "PancakeSwap",
    domain: "pancakeswap.finance",
    url: "https://pancakeswap.finance",
    description: "Decentralized exchange for swaps, liquidity, and DeFi products.",
    category: "DEX",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:07:00.000Z",
    clickCount: 0,
    logoText: "CAKE",
  },
  {
    id: "opensea",
    slug: "opensea",
    name: "OpenSea",
    domain: "opensea.io",
    url: "https://opensea.io",
    description: "Marketplace for NFTs, collectibles, and digital assets.",
    category: "NFT",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-17T10:45:00.000Z",
    clickCount: 5284,
    logoText: "OS",
  },
  {
    id: "blur",
    slug: "blur",
    name: "Blur",
    domain: "blur.io",
    url: "https://blur.io",
    description: "NFT marketplace and trading platform for professional collectors.",
    category: "NFT",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:08:00.000Z",
    clickCount: 0,
    logoText: "BLUR",
  },
  {
    id: "immutable",
    slug: "immutable",
    name: "Immutable",
    domain: "immutable.com",
    url: "https://www.immutable.com",
    description: "Web3 gaming platform and infrastructure for blockchain games.",
    category: "Gaming",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:09:00.000Z",
    clickCount: 0,
    logoText: "IMX",
  },
  {
    id: "lens",
    slug: "lens",
    name: "Lens",
    domain: "lens.xyz",
    url: "https://lens.xyz",
    description: "Social graph and app ecosystem for on-chain social experiences.",
    category: "SocialFi",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-08-16T13:25:00.000Z",
    clickCount: 4322,
    logoText: "LS",
  },
  {
    id: "coinbase",
    slug: "coinbase",
    name: "Coinbase",
    domain: "coinbase.com",
    url: "https://www.coinbase.com",
    description: "Crypto exchange, wallet, and on-chain application platform.",
    category: "Wallets",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-16T07:30:00.000Z",
    clickCount: 4106,
    logoText: "CB",
  },
  {
    id: "aave",
    slug: "aave",
    name: "Aave",
    domain: "aave.com",
    url: "https://aave.com",
    description: "Decentralized liquidity protocol for borrowing and supplying assets.",
    category: "DeFi",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-09-03T00:01:00.000Z",
    clickCount: 0,
    logoText: "AA",
  },
  {
    id: "celestia",
    slug: "celestia",
    name: "Celestia",
    domain: "celestia.org",
    url: "https://celestia.org",
    description: "Modular data availability network for rollups and app chains.",
    category: "Infrastructure",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-15T12:18:00.000Z",
    clickCount: 3460,
    logoText: "TIA",
  },
  {
    id: "base",
    slug: "base",
    name: "Base",
    domain: "base.org",
    url: "https://base.org",
    description: "Ethereum layer two network built for consumer crypto applications.",
    category: "L2",
    totalBidUsdt: 10,
    rankingTimestamp: "2026-08-14T20:52:00.000Z",
    clickCount: 3045,
    logoText: "B",
  },
  {
    id: "zora",
    slug: "zora",
    name: "Zora",
    domain: "zora.co",
    url: "https://zora.co",
    description: "On-chain creative network for minting and collecting media.",
    category: "NFT",
    totalBidUsdt: 5,
    rankingTimestamp: "2026-08-14T09:16:00.000Z",
    clickCount: 2718,
    logoText: "ZR",
  },
];

export function rankedProjects(projects = developmentProjects) {
  return [...projects].sort((a, b) => {
    if (a.totalBidUsdt !== b.totalBidUsdt) {
      return b.totalBidUsdt - a.totalBidUsdt;
    }

    return (
      new Date(a.rankingTimestamp).getTime() -
      new Date(b.rankingTimestamp).getTime()
    );
  });
}

export function getProjectRank(slug: string) {
  return rankedProjects().findIndex((project) => project.slug === slug) + 1;
}

export function formatUsdt(value: number | bigint) {
  return `${new Intl.NumberFormat("en-US").format(value)} USDT`;
}

export function getClaimTopBid(projects = developmentProjects) {
  const [top] = rankedProjects(projects);
  return top ? top.totalBidUsdt + 5 : 5;
}

export function getNextRankTarget(rank: number, projects = developmentProjects) {
  const ranked = rankedProjects(projects);
  if (rank <= 1) {
    return ranked[0] ? ranked[0].totalBidUsdt + 5 : 5;
  }

  const target = ranked[rank - 2];
  return target ? target.totalBidUsdt + 1 : 5;
}

export const developmentActivity = [
  {
    id: "a1",
    label: "Hyperliquid took #1",
    detail: "34 USDT",
    kind: "crown",
  },
  {
    id: "a2",
    label: "EigenLayer entered Infrastructure",
    detail: "29 USDT",
    kind: "boost",
  },
  {
    id: "a3",
    label: "Pendle entered DeFi",
    detail: "24 USDT",
    kind: "duel",
  },
  {
    id: "a4",
    label: "Mantle entered L2",
    detail: "21 USDT",
    kind: "move",
  },
  {
    id: "a5",
    label: "Ethena entered DeFi",
    detail: "18 USDT",
    kind: "boost",
  },
];
