const staticProjectIconSlugs = new Set([
  "uniswap",
  "hyperliquid",
  "eigenlayer",
  "pendle",
  "mantle",
  "ethena",
  "okx",
  "robinhood",
  "kraken",
  "avalanche",
  "sui",
  "polygon",
  "starknet",
  "the-graph",
  "filecoin",
  "akash-network",
  "lido",
  "makerdao",
  "curve",
  "dydx",
  "magic-eden",
  "axie-infinity",
  "farcaster",
  "shiba-inu",
  "uma",
  "centrifuge",
  "bittensor",
  "ethereum",
  "optimism",
  "chainlink",
  "solana",
  "arbitrum",
  "dogecoin",
  "render-network",
  "ondo-finance",
  "helium",
  "polymarket",
  "azuro",
  "phantom",
  "binance",
  "jupiter",
  "pancakeswap",
  "opensea",
  "blur",
  "immutable",
  "lens",
  "coinbase",
  "aave",
  "celestia",
  "base",
  "zora",
]);

export function staticProjectIconUrl(slug: string) {
  return staticProjectIconSlugs.has(slug)
    ? `/project-icons/${encodeURIComponent(slug)}.svg`
    : null;
}
